# Limpiar consola y configurar codificación
Clear-Host
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

# Asegurar que existe la ruta de salida para el reporte
$outputDir = "C:\Screenshare"
if (-not (Test-Path $outputDir)) { New-Item -Path $outputDir -ItemType Directory -Force | Out-Null }
$outputPath = "$outputDir\paths.txt"

# Cabecera estructurada para el archivo de reporte final
$reportLines = @(
    "=========================================================================",
    "               DETAILED PATHS FORENSIC SCAN REPORT                       ",
    "=========================================================================",
    "Scan Date: $((Get-Date).ToString('yyyy-MM-dd HH:mm:ss'))",
    "Generated by PATHS Audit Tool",
    "-------------------------------------------------------------------------`n"
)

# Dibujar el logo de PATHS en la consola
Write-Host " ______   ______  ______  __  __   ______ " -ForegroundColor Cyan
Write-Host "/\  __ \ /\  __ \/\__  _\/\ \_\ \ /\  ___\ " -ForegroundColor Cyan
Write-Host "\ \  __< \ \  __ \/_/\ \/\ \  __  \\ \___  \ " -ForegroundColor Cyan
Write-Host " \ \_\ \_\\ \_\ \_\ \ \_\ \ \_\ \_\ \_____\ " -ForegroundColor Cyan
Write-Host "  \/_/ /_/ \/_/\/_/  \/_/  \/_/\/_/ \/_____/ " -ForegroundColor Cyan
Write-Host "`n Made with love`n" -ForegroundColor Magenta

Write-Host "Scanning for non-Microsoft files & suspicious strings..." -ForegroundColor Gray
Write-Host "Output Target: $outputPath`n" -ForegroundColor Yellow

# Configurar rutas a escanear
$scanTargets = @(
    @{ Path = "C:\Windows\System32"; Name = "C:\Windows\System32" }
    @{ Path = "C:\Windows\SysWOW64"; Name = "C:\Windows\SysWOW64" }
    @{ Path = $env:TEMP; Name = "C:\Users\" + $env:USERNAME + "\AppData\Local\Temp" }
)

# Diccionario expandido de cadenas sospechosas (Cheats / Autoclicks / Injectors)
$cheatKeywords = @("autoclick", "clicker", "cheat", "hack", "macro", "triggerbot", "aimbot", "injector", "bypass", "vape", "reach")

$totalFilesChecked = 0
$nonMicrosoftFound = 0
$keywordMatchesFound = 0
$noSignatureFound = 0
$sampleArray = @()
$startTime = Get-Date

# Recorrer cada directorio objetivo
foreach ($target in $scanTargets) {
    if (-not (Test-Path $target.Path)) { continue }
    
    Write-Host "Scanning: $($target.Name)" -ForegroundColor Cyan
    
    # Buscar ejecutables, librerías, drivers y componentes binarios comunes
    $files = Get-ChildItem -Path $target.Path -Include *.exe, *.dll, *.sys, *.node -Recurse -File -ErrorAction SilentlyContinue
    
    $dirCheckedCount = 0
    $dirFoundCount = 0
    
    foreach ($file in $files) {
        $totalFilesChecked++
        $dirCheckedCount++
        
        # BARRA DE PROGRESO EN TIEMPO REAL
        if ($dirCheckedCount % 250 -eq 0) {
            Write-Host "  [>] Inspected: $dirCheckedCount files..." -ForegroundColor Gray
        }
        
        $isNonMicrosoft = $false
        $isKeywordMatch = $false
        $isUnsigned = $false
        $companyName = "Unknown / Unsigned"
        
        # 1. Filtro Forense Avanzado: Comprobar la firma o compañía del archivo
        $versionInfo = Get-ItemProperty -Path $file.FullName -ErrorAction SilentlyContinue | Select-Object -ExpandProperty VersionInfo -ErrorAction SilentlyContinue
        if ($null -ne $versionInfo) {
            # CORRECCIÓN AQUÍ: Uso correcto del método nativo .Trim()
            if ($null -ne $versionInfo.CompanyName -and $versionInfo.CompanyName.Trim() -ne "") {
                $companyName = $versionInfo.CompanyName
                if ($companyName -notmatch "Microsoft") {
                    $isNonMicrosoft = $true
                }
            } else {
                $isUnsigned = $true
            }
        } else {
            $isUnsigned = $true
        }
        
        # 2. Filtro Forense: Buscar cadenas de cheats en el nombre del archivo
        foreach ($kw in $cheatKeywords) {
            if ($file.Name -like "*$kw*") {
                $isKeywordMatch = $true
                break
            }
        }
        
        # Si cumple cualquiera de los criterios de sospecha, lo guardamos con sus detalles completos
        if ($isNonMicrosoft -or $isKeywordMatch -or $isUnsigned) {
            $dirFoundCount++
            
            if ($isNonMicrosoft) { $nonMicrosoftFound++ }
            if ($isKeywordMatch) { $keywordMatchesFound++ }
            if ($isUnsigned) { $noSignatureFound++ }
            
            $sizeMb = [math]::Round(($file.Length / 1MB), 2)
            $modDate = $file.LastWriteTime.ToString("yyyy-MM-dd HH:mm:ss")
            
            # Formato detallado para el bloc de notas final (Ruta + Metadatos)
            $logEntry = "Path: $($file.FullName)`n  └─ Modified: $modDate | Size: $sizeMb MB | Company: $companyName"
            if ($isKeywordMatch) { $logEntry += " [!] CRITICAL: Cheat Keyword Match [!]" }
            $logEntry += "`n"
            
            $reportLines += $logEntry
            $sampleArray += @{ Path = $file.FullName; Size = $sizeMb }
        }
    }
    
    Write-Host "  [✓] Done. Found: $dirFoundCount suspicious/non-Microsoft files." -ForegroundColor Green
}

# Añadir resumen estadístico detallado al final del archivo de texto
$endTime = Get-Date
$duration = New-TimeSpan -Start $startTime -End $endTime
$elapsedMinutes = [math]::Round($duration.TotalMinutes, 2)

$reportLines += "========================================================================="
$reportLines += "                           SUMMARY DETAILS                               "
$reportLines += "========================================================================="
$reportLines += "Total Scan Duration        : $elapsedMinutes minutes"
$reportLines += "Total System Files Checked : $totalFilesChecked"
$reportLines += "Total Anomalies Documented : $($sampleArray.Count)"
$reportLines += "  └─ Non-Microsoft Signatures : $nonMicrosoftFound"
$reportLines += "  └─ Unsigned / Naked Binaries: $noSignatureFound"
$reportLines += "  └─ Cheat Keyword Detections : $keywordMatchesFound"
$reportLines += "========================================================================="

# Escribir todo el reporte estructurado en el disco C:
$reportLines | Out-File -FilePath $outputPath -Encoding utf8 -Force

# Estadísticas detalladas finales visibles en la pantalla negra (Consola)
Write-Host "`nScan Complete c:" -ForegroundColor Green
Write-Host "  Time Elapsed      : $elapsedMinutes minutes" -ForegroundColor Gray
Write-Host "  Files Checked     : $totalFilesChecked" -ForegroundColor Gray
Write-Host "  Unsigned Binaries : $noSignatureFound" -ForegroundColor Yellow
Write-Host "  Cheat String Match: $keywordMatchesFound" -ForegroundColor Red
Write-Host "  Non-Microsoft     : $nonMicrosoftFound" -ForegroundColor Red
Write-Host "  Output Report     : $outputPath" -ForegroundColor Yellow

# Mostrar la muestra visual en la consola (Sample Paths)
Write-Host "`nSample paths:" -ForegroundColor Cyan
$samples = $sampleArray | Select-Object -First 5
foreach ($s in $samples) {
    if ($null -ne $s) {
        Write-Host "  $($s.Path) " -NoNewline -ForegroundColor Gray
        Write-Host "($($s.Size) MB)" -ForegroundColor Green
    }
}

# Firma personalizada
Write-Host "`nHit up @ikxpzl if you find any issues" -ForegroundColor Cyan

